# Generated by Django 5.2.7 on 2025-10-27 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='major_1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Primary Major'),
        ),
        migrations.AddField(
            model_name='profile',
            name='major_2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Secondary Major'),
        ),
        migrations.AddField(
            model_name='profile',
            name='minor_1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Primary Minor'),
        ),
        migrations.AddField(
            model_name='profile',
            name='minor_2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Secondary Minor'),
        ),
    ]
