# Generated by Django 5.2.7 on 2025-10-27 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_userprofile_role'),
        ('profiles', '0003_profile_major_1_profile_major_2_profile_minor_1_and_more'),
    ]

    operations = [
    ]
