# Generated by Django 5.2.7 on 2025-11-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_merge_20251027_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('collaborator', 'Collaborator'), ('staff', 'Staff'), ('admin', 'Admin')], default='student', max_length=20),
        ),
    ]
