# Generated by Django 5.2.7 on 2025-11-10 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='google_event_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
