# Generated by Django 5.2.7 on 2025-11-17 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_training_google_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='google_calendar_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
